#!/usr/bin/env bash
#setting up nginx server
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html
sudo bash -c 'cat << EOF > /etc/nginx/sites-available/redirect_me
server {
    listen 80;

    server_name _;

    location /redirect_me {
        return 301 https://onepiece.fandom.com/wiki/One_Piece_Wiki;
    }

    location / {
        try_files \$uri \$uri/ =404;
    }
}
EOF'
sudo ln -s /etc/nginx/sites-available/redirect_me /etc/nginx/sites-enabled/
sudo service nginx restart
